### ISSUE TITLE
No GUI in Ardour

### ISSUE THREAD

**Issue by leochras** [Dougal-s/Aether#31]
I don't get a GUI in Ardour, I only get a black screen. In Reaper, however, I can see the GUI. 

Ardour logs this line over and over again: 

`Root: unrecognized horizontal distance units ',000000sp'`

As I don't know if this is an issue with Ardour or the plugin itself, I opened an issue over at Ardour as well: https://tracker.ardour.org/view.php?id=9237

I've installed [this package](https://aur.archlinux.org/packages/aether.lv2) of Aether on Arch.

**Comment by Dougal-s** [comment]
Aether used to break when using non en_US locales, although it should have been fixed by 5a1a7f1f6001df35f4c6e600a83df777539be53e. This looks like it might be the same issue. Could you check if the binaries generated by the automated builds — https://github.com/Dougal-s/Aether/actions — throw the same error? Thanks!

**Comment by derkrasseleo** [comment]
The GNU version didn't work, I just got the "Ardour can't open this plugin" window. But the LLVM one seems to work, thanks!

**Comment by derkrasseleo** [comment]
Will there be a new release including this fix? If so, I can notify the maintainer of the [aur package](https://aur.archlinux.org/packages/aether.lv2)..
